packageExtensions:
  chalk@5.0.1:
    dependencies:
      "#ansi-styles": "npm:ansi-styles@6.1.1"
      "#supports-color": "npm:supports-color@9.2.2"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.3.cjs
