version: '2'
services:
  meili:
    image: getmeili/meilisearch
    environment:
      - MEILI_MASTER_KEY=kimubabo
    ports:
      - '127.0.0.1:7700:7700'
  redis:
    image: redis
    ports:
      - '127.0.0.1:6379:6379'
  postgres:
    image: postgres
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      - 'POSTGRES_PASSWORD=wowtest'
