version: '3'

services:
  db:
    image: postgres
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres